drop table if exists computer;
drop table if exists company;
drop table if exists user_role cascade;
drop table if exists role;
drop table if exists user;

create table company (
    ca_id                        bigint not null generated by default as identity(start with 1, increment by 1),
    ca_name                      varchar(255) not null,
    constraint pk_company primary key (ca_id))
;

create table computer (
    cu_id                        bigint not null generated by default as identity(start with 1, increment by 1),
    cu_name                      varchar(255),
    cu_introduced                datetime NULL,
    cu_discontinued              datetime NULL,
    ca_id                bigint default NULL,
    constraint pk_computer primary key (cu_id),
    constraint fk_company foreign key (ca_id) references company(ca_id))
;

  create table user (
    us_id  bigint not null generated by default as identity(start with 1, increment by 1),
    us_username varchar(255) unique not null,
    us_password varchar(255) not null,
	constraint pk_user primary key (us_id)
  );
  
  create table role (
	ro_id  bigint not null generated by default as identity(start with 1, increment by 1),
    ro_label varchar(255) unique not null,
    constraint pk_role primary key (ro_id)
  );
  
  create table user_role (
	us_id bigint not null,
    ro_id bigint not null,
	constraint pk_user_role primary key (us_id, ro_id),
    constraint fk_user1 foreign key (us_id) references user(us_id),
    constraint fk_role foreign key (ro_id) references role(ro_id)
  );

insert into company (ca_id,ca_name) values (1,'Company 1');
insert into company (ca_id,ca_name) values (2,'Company 2');
insert into company (ca_id,ca_name) values (3,'COmpany 3');

insert into computer (cu_id,cu_name,cu_introduced,cu_discontinued,ca_id) values (1,'Computer 1','0001-01-01','0001-01-02',1);
insert into computer (cu_id,cu_name,cu_introduced,cu_discontinued,ca_id) values (2,null,null,null,null);
insert into computer (cu_id,cu_name,cu_introduced,cu_discontinued,ca_id) values (3,'Computer 3',null,'1994-09-12', 3);

insert into user (us_id, us_username, us_password) values (1, 'admin', '$2a$11$m4Gi9.oZ1iGtNT84zdkH9OknhHSju8yv6cbqn1NANs5UDaMyb4Mvu');
insert into user (us_id, us_username, us_password) values (2, 'user', '$2a$11$A3rJSGrB6UkhSQJRgRop0OQuozKz4mXilmAhDOH9mg7anXPChl11O');
insert into role (ro_id, ro_label) values (1, 'ROLE_ADMIN');  
insert into role (ro_id, ro_label) values (2, 'ROLE_USER');
insert into user_role (us_id, ro_id) values (1, 1);
insert into user_role (us_id, ro_id) values (1, 2);
insert into user_role (us_id, ro_id) values (2, 2);